name: Frontend CI
permissions:
  contents: read

on:
  pull_request:
    branches: ["main", "dev"]
  push:
    branches: ["dev"]

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: TypeCheck
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build